people:
  pi: "Prof Antoine van Kampen"
  bioinformatician: "Barbera van Schaik"
  collaborator: "Prof. dr. Jane Doe"
  laboratory_contact: "Dr John Doe"

sequence_run:
  run: runNN-20240528-nextseq
  outdir: 20240528-reseda
  webdavroot: https://researchdrive.surfsara.nl/remote.php/webdav/amc-immunogenomics/RUNS/
  machine: "Illumina NextSeq"

git:
  encore: git@github.com:EDS-Bioinformatics-Laboratory/ENCORE.git
  reseda: git@github.com:EDS-Bioinformatics-Laboratory/reseda.git

storage:
  rclone_root: "remote:amc-immunogenomics/RUNS/"
